---
- name: Installing httpd
  hosts: all
  become: true

  tasks:
  - name: Installing on redhat
    yum:
      name: httpd
      state: present
    when: ansible_os_family == "RedHat"

  - name: enabling on redhat
    service:
      name: httpd
      state: started
      enabled: true
    when: ansible_os_family == "RedHat"

  - name: installing apache2 on ubuntu
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Ubuntu"
