---
- name: Firewall changes
  hosts: all
  become: true

  tasks:
  - name: Enable firewalld
    firewalld:
      #service: nginx #or we can also give port
      port: 80/tcp
      permanent: true
      state: enabled #or disabled
  - name: Reload the firewalld
    service:
      name: firewalld
      state: reloaded


