---
- name: Environmental variable
  hosts: all

  tasks:
  - name: adding variable
    cron:
      name: VARR
      env: yes
      user: vagrant
      job: /tmp/tesh.sh
      state: absent # to remove the variable if already exist
