# supported urls http,https or ftp
---
- name: remote file download
  hosts: all
  become: true
  
  tasks:
  - name: Download file
    get_url:
      url: https://www.tooplate.com/zip-templates/2154_split_portfolio.zip
      dest: /tmp
      owner: vagrant
      group: vagrant
      mode: 0777
