---
- name: Install nginx on all servers
  hosts: all
  become: true
    #become_method: sudo
  tasks:
   - name: installing the nginx
     yum:
       name: nginx
       state: present
     tags: install-nginx
   - name: starting the service
     service:
       name: nginx
       state: started
       enabled: true
     tags: service-nginx
